More informative error message when GL widget isn't found.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4108,14 +4108,16 @@ fi
 echo "$ac_t""$sim_cv_motif_glwidget" 1>&6
 
 if test "x$sim_cv_motif_glwidget" = "xUNKNOWN"; then
-  { echo "configure: error: couldn't find Xt/Motif support for GL" 1>&2; exit 1; }
+  { echo "configure: error: couldn't find Xt/Motif support for GL.
+    A GL widget for Motif/LessTif can be found in the Mesa sources in the
+    mesa-widget/ directory.  This widget does not depend on using Mesa." 1>&2; exit 1; }
 else
   sim_ac_motif_glwidget_class=`echo $sim_cv_motif_glwidget | cut -d" " -f1`
   sim_ac_motif_glwidget_header=`echo $sim_cv_motif_glwidget | cut -d" " -f2`
   sim_ac_motif_glwidget_library=`echo $sim_cv_motif_glwidget | cut -d" " -f3`
 
   echo $ac_n "checking the $sim_ac_motif_glwidget_header header location... $ac_c" 1>&6
-echo "configure:4119: checking the $sim_ac_motif_glwidget_header header location" 1>&5
+echo "configure:4121: checking the $sim_ac_motif_glwidget_header header location" 1>&5
 if test "${sim_cv_motif_glwidget_hdrloc+set}" = set; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -4123,13 +4125,13 @@ else
     for location in X11/GLw GL; do
       if test "x$sim_cv_motif_glwidget_hdrloc" = "xUNKNOWN"; then
         cat >conftest.$ac_ext <<EOF
-#line 4127 "configure"
+#line 4129 "configure"
 #include "confdefs.h"
 #include <X11/Intrinsic.h>
           #include <$location/$sim_ac_motif_glwidget_header>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:4133: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:4135: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -4148,7 +4150,9 @@ fi
 echo "$ac_t""$sim_cv_motif_glwidget_hdrloc" 1>&6
 
   if test "x$sim_cv_motif_glwidget_hdrloc" = "xUNKNOWN"; then
-    { echo "configure: error: couldn't find Xt/Motif support for GL" 1>&2; exit 1; }
+    { echo "configure: error: couldn't find Xt/Motif support for GL.
+    A GL widget for Motif/LessTif can be found in the Mesa sources in the
+    mesa-widget/ directory.  This widget does not depend on using Mesa." 1>&2; exit 1; }
   else
     if test "x$sim_ac_motif_glwidget_header" = "xGLwDrawA.h"; then
       if test "x$sim_cv_motif_glwidget_hdrloc" = "xGL"; then
@@ -4206,7 +4210,7 @@ fi
 sim_ac_ivexamples_available=no
 if test x"${with_ivexamples+set}" = x"set"; then
   echo $ac_n "checking for ivexamples directory... $ac_c" 1>&6
-echo "configure:4210: checking for ivexamples directory" 1>&5
+echo "configure:4214: checking for ivexamples directory" 1>&5
   if test -f ${srcdir}/ivexamples/configure.in; then
     echo "$ac_t""found" 1>&6
     sim_ac_ivexamples_available=yes
