Configure-script with the new GL widget check.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3422,8 +3422,8 @@ if test x"$with_motif" != xno; then
   LDFLAGS="$sim_ac_motif_ldflags $LDFLAGS"
   LIBS="$sim_ac_motif_libs $LIBS"
 
-  echo $ac_n "checking for Motif development kit... $ac_c" 1>&6
-echo "configure:3427: checking for Motif development kit" 1>&5
+  echo $ac_n "checking for a Motif development environment... $ac_c" 1>&6
+echo "configure:3427: checking for a Motif development environment" 1>&5
 if test "${sim_cv_lib_motif_avail+set}" = set; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -3462,287 +3462,154 @@ fi
 
 
 
-
-echo $ac_n "checking location of GL widget header file... $ac_c" 1>&6
-echo "configure:3468: checking location of GL widget header file" 1>&5
-if test "${sim_cv_header_glw+set}" = set; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  
-  cat >conftest.$ac_ext <<EOF
-#line 3474 "configure"
-#include "confdefs.h"
-#include <GL/GLwMDrawA.h>
-EOF
-ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:3479: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
-ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
-if test -z "$ac_err"; then
-  rm -rf conftest*
-  sim_cv_header_glw="GL/GLwMDrawA.h"
-else
-  echo "$ac_err" >&5
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  sim_cv_header_glw=UNRESOLVED
-fi
-rm -f conftest*
-  if test x"$sim_cv_header_glw" = xUNRESOLVED; then
-    cat >conftest.$ac_ext <<EOF
-#line 3494 "configure"
-#include "confdefs.h"
-#include <X11/GLw/GLwMDrawA.h>
-EOF
-ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:3499: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
-ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
-if test -z "$ac_err"; then
-  rm -rf conftest*
-  sim_cv_header_glw="X11/GLw/GLwMDrawA.h"
-else
-  echo "$ac_err" >&5
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  sim_cv_header_glw=UNRESOLVED
-fi
-rm -f conftest*
-  fi
-  if test x"$sim_cv_header_glw" = xUNRESOLVED; then
-    cat >conftest.$ac_ext <<EOF
-#line 3515 "configure"
-#include "confdefs.h"
-#include <GL/GLwDrawA.h>
-EOF
-ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:3520: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
-ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
-if test -z "$ac_err"; then
-  rm -rf conftest*
-  sim_cv_header_glw="GL/GLwDrawA.h"
-else
-  echo "$ac_err" >&5
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  sim_cv_header_glw=UNRESOLVED
-fi
-rm -f conftest*
-  fi
-  if test x"$sim_cv_header_glw" = xUNRESOLVED; then
-    cat >conftest.$ac_ext <<EOF
-#line 3536 "configure"
-#include "confdefs.h"
-#include <X11/GLw/GLwDrawA.h>
-EOF
-ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:3541: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
-ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
-if test -z "$ac_err"; then
-  rm -rf conftest*
-  sim_cv_header_glw="X11/GLw/GLwDrawA.h"
-else
-  echo "$ac_err" >&5
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  sim_cv_header_glw=UNRESOLVED
-fi
-rm -f conftest*
-  fi
-
-fi
-echo "$ac_t""$sim_cv_header_glw" 1>&6
-
-if test x"$sim_cv_header_glw" = "xGL/GLwMDrawA.h"; then
-  cat >>confdefs.h <<\EOF
-#define HAVE_GL_GLWMDRAWA_H 1
-EOF
-
-  sim_ac_glwidget=glwMDrawingAreaWidgetClass
-elif test x"$sim_cv_header_glw" = "xX11/GLw/GLwMDrawA.h"; then
-  cat >>confdefs.h <<\EOF
-#define HAVE_X11_GLW_GLWMDRAWA_H 1
-EOF
-
-  sim_ac_glwidget=glwMDrawingAreaWidgetClass
-elif test x"$sim_cv_header_glw" = "xGL/GLwDrawA.h"; then
-  cat >>confdefs.h <<\EOF
-#define HAVE_GL_GLWDRAWA_H 1
-EOF
-
-  sim_ac_glwidget=glwDrawingAreaWidgetClass
-elif test x"$sim_cv_header_glw" = "xX11/GLw/GLwDrawA.h"; then
-  cat >>confdefs.h <<\EOF
-#define HAVE_X11_GLW_GLWDRAWA_H 1
-EOF
-
-  sim_ac_glwidget=glwDrawingAreaWidgetClass
-elif test x"$sim_cv_header_glw" = xUNRESOLVED; then
-  echo "configure: warning: Could not find GLwMDrawA.h" 1>&2
-  sim_ac_glwidget=0
-else
-  { echo "configure: error: macro programming error" 1>&2; exit 1; }
-fi
-
-cat >>confdefs.h <<EOF
-#define GLW_WIDGETCLASS $sim_ac_glwidget
-EOF
-
-
-if test x"$sim_cv_header_glw" = xUNRESOLVED; then
-  :
-else
-  :
-fi
-
-
-
-
-
-echo $ac_n "checking for library containing glwMDrawingAreaWidgetClass... $ac_c" 1>&6
-echo "configure:3606: checking for library containing glwMDrawingAreaWidgetClass" 1>&5
-if test "${sim_cv_lib_glw+set}" = set; then
+echo $ac_n "checking for a GL widget... $ac_c" 1>&6
+echo "configure:3467: checking for a GL widget" 1>&5
+if test "${sim_cv_motif_glwidget+set}" = set; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   
   SAVELIBS=$LIBS
-  LIBS="$SAVELIBS -lMesaGLwM"
-  cat >conftest.$ac_ext <<EOF
-#line 3614 "configure"
+  sim_cv_motif_glwidget=UNKNOWN
+  for lib in GLwM GLw MesaGLwM MesaGLw; do
+    if test "x$sim_cv_motif_glwidget" = "xUNKNOWN"; then
+      LIBS="$SAVELIBS -l$lib"
+      cat >conftest.$ac_ext <<EOF
+#line 3478 "configure"
 #include "confdefs.h"
- #include <X11/Intrinsic.h>
-                #include <$sim_cv_header_glw> 
+
+        #include <X11/Intrinsic.h>
+        extern WidgetClass glwMDrawingAreaWidgetClass;
+        
 int main() {
- WidgetClass x = glwMDrawingAreaWidgetClass; 
+WidgetClass w = glwMDrawingAreaWidgetClass
 ; return 0; }
 EOF
-if { (eval echo configure:3622: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3488: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
-  sim_cv_lib_glw="-lMesaGLwM"
+  sim_cv_motif_glwidget="glwMDrawingAreaWidgetClass GLwMDrawA.h $lib"
 else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
   rm -rf conftest*
-  sim_cv_lib_glw="UNRESOLVED"
+  sim_cv_motif_glwidget=UNKNOWN
 fi
 rm -f conftest*
-  if test "x$sim_cv_lib_glw" = "xUNRESOLVED"; then
-    LIBS="$SAVELIBS -lGLw"
-    cat >conftest.$ac_ext <<EOF
-#line 3635 "configure"
+    fi
+    if test "x$sim_cv_motif_glwidget" = "xUNKNOWN"; then
+      LIBS="$SAVELIBS -l$lib"
+      cat >conftest.$ac_ext <<EOF
+#line 3502 "configure"
 #include "confdefs.h"
- #include <X11/Intrinsic.h>
-                  #include <$sim_cv_header_glw> 
+
+        #include <X11/Intrinsic.h>
+        extern WidgetClass glwDrawingAreaWidgetClass;
+      
 int main() {
- WidgetClass x = glwMDrawingAreaWidgetClass; 
+WidgetClass w = glwDrawingAreaWidgetClass
 ; return 0; }
 EOF
-if { (eval echo configure:3643: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3512: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
-  sim_cv_lib_glw="-lGLw"
+  sim_cv_motif_glwidget="glwDrawingAreaWidgetClass GLwDrawA.h $lib"
 else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
   rm -rf conftest*
-  sim_cv_lib_glw="UNRESOLVED"
+  sim_cv_motif_glwidget=UNKNOWN
 fi
 rm -f conftest*
-  fi
-  if test "x$sim_cv_lib_glw" = "xUNRESOLVED"; then
-    LIBS="$SAVELIBS -lMesaGLw"
-    cat >conftest.$ac_ext <<EOF
-#line 3657 "configure"
-#include "confdefs.h"
- #include <X11/Intrinsic.h>
-                  #include <$sim_cv_header_glw> 
-int main() {
- WidgetClass x = glwDrawingAreaWidgetClass; 
-; return 0; }
-EOF
-if { (eval echo configure:3665: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
-  rm -rf conftest*
-  sim_cv_lib_glw="-lMesaGLw"
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  sim_cv_lib_glw="UNRESOLVED"
-fi
-rm -f conftest*
-  fi
-  if test "x$sim_cv_lib_glw" = "xUNRESOLVED"; then
-    LIBS="$SAVELIBS -lGLw"
-    cat >conftest.$ac_ext <<EOF
-#line 3679 "configure"
-#include "confdefs.h"
- #include <X11/Intrinsic.h>
-                  #include <$sim_cv_header_glw> 
-int main() {
- WidgetClass x = glwDrawingAreaWidgetClass; 
-; return 0; }
-EOF
-if { (eval echo configure:3687: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
-  rm -rf conftest*
-  sim_cv_lib_glw="-lGLw"
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  sim_cv_lib_glw="UNRESOLVED"
-fi
-rm -f conftest*
-  fi
+    fi
+  done
   LIBS=$SAVELIBS
-
+  
 fi
-echo "$ac_t""$sim_cv_lib_glw" 1>&6
+echo "$ac_t""$sim_cv_motif_glwidget" 1>&6
 
-
-if test "x$sim_cv_lib_glw" = "xUNRESOLVED"; then
-  :
+if test "x$sim_cv_motif_glwidget" = "xUNKNOWN"; then
+  { echo "configure: error: couldn't find Xt/Motif support for GL" 1>&2; exit 1; }
 else
-  LIBS="$LIBS $sim_cv_lib_glw"
-  :
-fi
+  sim_ac_motif_glwidget_class=`echo $sim_cv_motif_glwidget | cut -d" " -f1`
+  sim_ac_motif_glwidget_header=`echo $sim_cv_motif_glwidget | cut -d" " -f2`
+  sim_ac_motif_glwidget_library=`echo $sim_cv_motif_glwidget | cut -d" " -f3`
 
-
-
-
-sim_ac_save_cppflags=$CPPFLAGS
-sim_ac_save_ldflags=$LDFLAGS
-sim_ac_save_libs=$LIBS
-
-
-echo $ac_n "checking for the Xt/Motif GLw development environment... $ac_c" 1>&6
-echo "configure:3720: checking for the Xt/Motif GLw development environment" 1>&5
-if test "${sim_cv_dev_glw+set}" = set; then
+  echo $ac_n "checking the $sim_ac_motif_glwidget_header header location... $ac_c" 1>&6
+echo "configure:3537: checking the $sim_ac_motif_glwidget_header header location" 1>&5
+if test "${sim_cv_motif_glwidget_hdrloc+set}" = set; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
-   sim_cv_dev_glw=yes
-  if test x"$sim_cv_header_glw" = xUNRESOLVED; then
-    sim_cv_dev_glw=no
-  elif test x"$sim_cv_lib_glw" = xUNRESOLVED; then
-    sim_cv_dev_glw=no
-  fi
-
-fi
-echo "$ac_t""$sim_cv_dev_glw" 1>&6
-
-if test x$sim_cv_dev_glw = xyes; then
-  :
+  
+    sim_cv_motif_glwidget_hdrloc=UNKNOWN
+    for location in X11/GLw GL; do
+      if test "x$sim_cv_motif_glwidget_hdrloc" = "xUNKNOWN"; then
+        cat >conftest.$ac_ext <<EOF
+#line 3546 "configure"
+#include "confdefs.h"
+ #include <X11/Intrinsic.h>
+                     #include <$location/$sim_ac_motif_glwidget_header> 
+EOF
+ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
+{ (eval echo configure:3552: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
+if test -z "$ac_err"; then
+  rm -rf conftest*
+  sim_cv_motif_glwidget_hdrloc=$location
 else
-  CPPFLAGS=$sim_ac_save_cppflags
-  LDFLAGS=$sim_ac_save_ldflags
-  LIBS=$sim_ac_save_libs
-  { echo "configure: error: couldn't compile and link with the Motif glwMDrawingAreaWidgetClass extension" 1>&2; exit 1; }
+  echo "$ac_err" >&5
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  sim_cv_motif_glwidget_hdrloc=UNKNOWN
 fi
+rm -f conftest*
+      fi
+    done
+    
+fi
+echo "$ac_t""$sim_cv_motif_glwidget_hdrloc" 1>&6
+
+  if test "x$sim_cv_motif_glwidget_hdrloc" = "xUNKNOWN"; then
+    { echo "configure: error: couldn't find Xt/Motif support for GL" 1>&2; exit 1; }
+  else
+    if test "x$glwidget_header" = "xGLwDrawA.h"; then
+      if test "x$sim_cv_motif_glwidget_hdrloc" = "xGL"; then
+        cat >>confdefs.h <<\EOF
+#define HAVE_GL_GLWDRAWA_H 
+EOF
+
+      else
+        cat >>confdefs.h <<\EOF
+#define HAVE_X11_GLW_GLWDRAWA_H 
+EOF
+
+      fi
+    else
+      if test "x$sim_cv_motif_glwidget_hdrloc" = "xGL"; then
+        cat >>confdefs.h <<\EOF
+#define HAVE_GL_GLWMDRAWA_H 
+EOF
+
+      else
+        cat >>confdefs.h <<\EOF
+#define HAVE_X11_GLW_GLWMDRAWA_H 
+EOF
+
+      fi
+    fi
+
+    cat >>confdefs.h <<EOF
+#define XT_GLWIDGET $sim_ac_motif_glwidget_class
+EOF
+
+
+    LIBS="$LIBS -l$sim_ac_motif_glwidget_library"
+
+    :
+  fi
+fi
+
 
 
 CXXFLAGS="$CXXFLAGS -DSOXT_DEBUG=1"
-COMPONENTLIBS=""
-# $sim_cv_lib_glw
 
 
 
@@ -3816,7 +3683,7 @@ COMPONENTHEADER=""
 
 
 
-
+COMPONENTLIBS=""
 
 
 
