Generate cfg-file(s) from common template.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12391,7 +12391,7 @@ subdirs="$subdirs data"
 # **************************************************************************
 # generate the makefiles and config files.
 
-ac_config_files="$ac_config_files Makefile soxt-$CONFIG.cfg:soxt.cfg.in src/Makefile src/Inventor/Makefile src/Inventor/Xt/Makefile src/Inventor/Xt/devices/Makefile src/Inventor/Xt/widgets/Makefile src/Inventor/Xt/viewers/Makefile build/soxt.spec build/soxt.doxygen"
+ac_config_files="$ac_config_files Makefile src/Makefile src/Inventor/Makefile src/Inventor/Xt/Makefile src/Inventor/Xt/devices/Makefile src/Inventor/Xt/widgets/Makefile src/Inventor/Xt/viewers/Makefile build/soxt.spec build/soxt.doxygen"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -12712,7 +12712,6 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
-  "soxt-$CONFIG.cfg" ) CONFIG_FILES="$CONFIG_FILES soxt-$CONFIG.cfg:soxt.cfg.in" ;;
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "src/Inventor/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Inventor/Makefile" ;;
   "src/Inventor/Xt/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Inventor/Xt/Makefile" ;;
@@ -12723,7 +12722,7 @@ do
   "build/soxt.doxygen" ) CONFIG_FILES="$CONFIG_FILES build/soxt.doxygen" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "src/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS src/config.h" ;;
-  *) { { echo "$as_me:12726: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:12725: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -13017,7 +13016,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:13020: creating $ac_file" >&5
+    { echo "$as_me:13019: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -13035,7 +13034,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:13038: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:13037: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -13048,7 +13047,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:13051: error: cannot find input file: $f" >&5
+           { { echo "$as_me:13050: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -13109,7 +13108,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:13112: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:13111: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -13120,7 +13119,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:13123: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:13122: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -13133,7 +13132,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:13136: error: cannot find input file: $f" >&5
+           { { echo "$as_me:13135: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -13250,7 +13249,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:13253: $ac_file is unchanged" >&5
+      { echo "$as_me:13252: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -13412,7 +13411,7 @@ if test "$no_recursion" != yes; then
     # parts of a large source tree are present.
     test -d $srcdir/$ac_subdir || continue
 
-    { echo "$as_me:13415: configuring in $ac_subdir" >&5
+    { echo "$as_me:13414: configuring in $ac_subdir" >&5
 echo "$as_me: configuring in $ac_subdir" >&6;}
     case $srcdir in
     .) ;;
@@ -13434,7 +13433,7 @@ done; }
 
        if test -d ./$ac_subdir; then :;
        else
-         { { echo "$as_me:13437: error: cannot create \`pwd\`/$ac_subdir" >&5
+         { { echo "$as_me:13436: error: cannot create \`pwd\`/$ac_subdir" >&5
 echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
        fi
@@ -13465,7 +13464,7 @@ echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
     elif test -f $ac_sub_srcdir/configure.in; then
       ac_sub_configure=$ac_configure
     else
-      { echo "$as_me:13468: WARNING: no configuration information is in $ac_subdir" >&5
+      { echo "$as_me:13467: WARNING: no configuration information is in $ac_subdir" >&5
 echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
       ac_sub_configure=
     fi
@@ -13479,12 +13478,12 @@ echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
         ac_sub_cache_file=$ac_dots$cache_file ;;
       esac
 
-      { echo "$as_me:13482: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
+      { echo "$as_me:13481: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
 echo "$as_me: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&6;}
       # The eval makes quoting arguments work.
       eval $ac_sub_configure $ac_sub_configure_args \
            --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir ||
-        { { echo "$as_me:13487: error: $ac_sub_configure failed for $ac_subdir" >&5
+        { { echo "$as_me:13486: error: $ac_sub_configure failed for $ac_subdir" >&5
 echo "$as_me: error: $ac_sub_configure failed for $ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
     fi
