Upgrade to CVS Autoconf and CVS Automake.

diff --git a/soxt-config.in b/soxt-config.in
--- a/soxt-config.in
+++ b/soxt-config.in
@@ -1,32 +1,26 @@
-#!/bin/sh
-
-
-###### SUBROUTINES ########################################################
+#! /bin/sh
+############################################################################
 
 usage()
 {
 cat <<EOF
-    Usage: soxt-config [OPTIONS]
-    Options:
-            [--version]
-            [--cppflags]
-            [--ldflags]
-            [--libs]
+Usage: soxt-config [OPTIONS]
+Options:
+  --help | --usage
+  --cppflags
+  --ldflags
+  --libs
+  --datadir
+  --ac-subst <subst>
+  --have-feature <feature>
+  --build <program> <sourcefile> [<sourcefile>]...
+  --version
 EOF
   exit $1
 }
 
-###### MAIN ###############################################################
-
-if test $# -eq 0; then
-  usage 1 1>&2
-fi
-
 while test $# -gt 0; do
   case $1 in
-    --version)
-      echo @SOXT_VERSION@
-      ;;
     --cppflags)
       # Note: if we for some reason changes this so "includedir" is
       # not first, we need to fix up the examples/ and ivexamples/
@@ -38,6 +32,55 @@ while test $# -gt 0; do
       ;;
     --libs)
       echo -lSoXt @SOXT_EXTRA_LIBS@
+      ;;
+    --datadir)
+      echo @soxt_data_dir@
+      ;;
+    --version)
+      echo @SOXT_VERSION@
+      ;;
+    --help | --usage)
+      usage 0
+      ;;
+    --ac-subst)
+      shift
+      case $1 in
+        GUI)             echo "@GUI@" ;;
+        Gui)             echo "@Gui@" ;;
+        gui)             echo "@gui@" ;;
+        WIDGET)          echo "@WIDGET@" ;;
+        WINWIDGET)       echo "@WINWIDGET@" ;;
+        EVENT)           echo "@EVENT@" ;;
+        COMPONENTHEADER) echo "@COMPONENTHEADER@" ;;
+        *)
+          echo "Error: no such AC_SUBST: $1" >&2
+          exit 1
+          ;;
+      esac
+      ;;
+    --have-feature)
+      shift
+      case $1 in
+        renderarea)       exit 0 ;;
+        examinerviewer)   exit 0 ;;
+        planeviewer)      exit 0 ;;
+        walkviewer)       exit 0 ;;
+        flyviewer)        exit 0 ;;
+        materiallist)     exit 0 ;;
+        *) exit 1 ;;
+      esac
+      ;;
+    --build)
+      shift
+      program=$1
+      shift
+      set -x
+      @CXX@ \
+        ${CPPFLAGS} @SOXT_EXTRA_CPPFLAGS@ \
+        ${LDFLAGS} @SOXT_EXTRA_LDFLAGS@ \
+        -o ${program} $@ \
+        ${LIBS} @SOXT_EXTRA_LIBS@
+      set +x
       ;;
     *)
       echo "Unknown option: \"$1\""
